server:
  port: 9527

spring:
  application:
    name: spring-cloud-gateway-sample
  cloud:
    gateway:
      discovery:
      locator:
      enabled: true
      routes:
      - id: path_route
        uri: http://news.baidu.com
        predicates:
        - Path=/guonei

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
